# ----- Homebrew -----
if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x /usr/local/bin/brew ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi

# ----- Bash Completions -----
[[ -r /opt/homebrew/etc/profile.d/bash_completion.sh ]] &&
  source /opt/homebrew/etc/profile.d/bash_completion.sh

# ----- Zsh Completion -----
autoload -Uz compinit
compinit

# ----- Prompt -----
if [[ -f ~/git-prompt.sh ]]; then
  source ~/git-prompt.sh

  precmd() {
    __posh_git_ps1 '%n@%m:%~ ' ' $ '
  }
fi

# ----- Dotfiles -----
[[ -f ~/.zsh-aliases ]] && source ~/.zsh-aliases
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local